Bump gridsuite dependencies to 32
gridsuite/shortcircuit-server pull request #108
Opened 2024-09-10 15:30 UTC by YenguiSeddik

2024-09-11 07:31 UTC, AbdelHedhili requested changes

2024-09-11 07:31 UTC, AbdelHedhili commented on src/main/resources/config/application.yaml
> +      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishFailed-out-0:publishCancelFailed
publishCancelFailed-out-0 ?

2024-09-11 07:48 UTC, YenguiSeddik commented on src/main/resources/config/application.yaml
> +      output-bindings: publishRun-out-0;publishResult-out-0;publishCancel-out-0;publishStopped-out-0;publishFailed-out-0:publishCancelFailed
done

2024-09-11 11:47 UTC, AbdelHedhili approved these changes

2024-09-12 07:07 UTC, sBouzols approved these changes

2024-09-12 08:11 UTC, merged