Allow short circuit analysis even when missing ISC min and max
gridsuite/shortcircuit-server pull request #69
Opened 2024-01-09 09:17 UTC by ne0ds

2024-01-10 12:52 UTC, etiennehomer requested changes
Tests ok

2024-01-10 12:52 UTC, etiennehomer commented on src/test/java/org/gridsuite/shortcircuit/server/repositories/FaultResultRepositoryTest.java
> +        shortCircuitAnalysisResultRepository.insert(MAGNITUDE_RESULT_UUID, RESULT_MAGNITUDE_FULL, new ShortCircuitRunContext(
Define a constant for  new ShortCircuitRunContext() and use it everywhere

2024-01-10 12:52 UTC, etiennehomer commented on src/main/java/org/gridsuite/shortcircuit/server/repositories/ShortCircuitAnalysisResultRepository.java
> +    public void insert(UUID resultUuid, ShortCircuitAnalysisResult result, ShortCircuitRunContext runContext, String status) {
You can also give currentLimits and busId as distinct parameters

2024-01-11 08:13 UTC, Meklo approved these changes

2024-01-11 08:56 UTC, etiennehomer approved these changes

2024-01-11 10:14 UTC, Tristan-WorkGH approved these changes

2024-01-11 10:19 UTC, merged