add error logs when voltage levels have ip_mi > ip_max
gridsuite/shortcircuit-server pull request #95
Opened 2024-06-10 12:49 UTC by EtienneLt

2024-06-17 11:24 UTC, etiennehomer requested changes

2024-06-17 11:24 UTC, etiennehomer commented on src/main/java/org/gridsuite/shortcircuit/server/reports/ReportMapperShortCircuit.java
> +        if (!runContext.getInconsistentVoltageLevels().isEmpty()) {
This condition should be before the run of the computation. If true, we store a failed status, an empty result and the reports that you build in forVoltageLevelsWithWrongIpValues

2024-07-04 15:25 UTC, etiennehomer requested changes

2024-07-04 15:25 UTC, etiennehomer commented on src/main/java/org/gridsuite/shortcircuit/server/service/ShortCircuitWorkerService.java
> +            throw new ShortCircuitException(INCONSISTENT_VOLTAGE_LEVELS, "Some voltage levels have wrong ip values check logs to find which");
```suggestion
            throw new ShortCircuitException(INCONSISTENT_VOLTAGE_LEVELS, "Some voltage levels have wrong isc values. Check out the logs to find which ones.");
```

2024-07-08 08:58 UTC, EtienneLt commented
rebase and fixed in https://github.com/gridsuite/shortcircuit-server/pull/100

2024-07-08 08:58 UTC, closed without merging