reset extension data error message
gridsuite/shortcircuit-server pull request #99
Opened 2024-07-05 14:40 UTC by Mathieu-Deharbe

lost during the generic computation classes update

2024-07-08 11:26 UTC, EtienneLt approved these changes

2024-07-09 12:27 UTC, etiennehomer requested changes

2024-07-09 12:27 UTC, etiennehomer commented on src/main/java/org/gridsuite/shortcircuit/server/service/ShortCircuitWorkerService.java
> +        } else {
you can remove the "else"

2024-07-09 13:01 UTC, etiennehomer reviewed
It would be nice to have a small unit test on this case

2024-07-09 15:53 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/shortcircuit/server/service/ShortCircuitWorkerService.java
> +        } else {
Done.

2024-07-10 08:48 UTC, Mathieu-Deharbe commented
> It would be nice to have a small unit test on this case

Indeed, that would be dumb to encounter the same problem agin. There was already a test but dysfunctional. I corrected it and added a specific network for it.

2024-07-10 09:25 UTC, etiennehomer approved these changes

2024-07-10 09:27 UTC, merged